"use client";
// Importing required modules and styles
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

// Interface for the component state
interface HomeState {
  num1: string;
  num2: string;
  result: number;
}

// React functional component with TypeScript
export default function Home(): JSX.Element {
  // State initialization using useState hook
  const [state, setState] = useState<HomeState>({
    num1: "0",
    num2: "0",
    result: 0,
  });

  // Event handlers for arithmetic operations
  const add = (): void => {
    setState((prev) => ({
      ...prev,
      result: parseInt(prev.num1) + parseInt(prev.num2),
    }));
  };

  const subtract = (): void => {
    setState((prev) => ({
      ...prev,
      result: parseInt(prev.num1) - parseInt(prev.num2),
    }));
  };

  const multiply = (): void => {
    setState((prev) => ({
      ...prev,
      result: parseInt(prev.num1) * parseInt(prev.num2),
    }));
  };

  const divide = (): void => {
    setState((prev) => ({
      ...prev,
      result: parseInt(prev.num1) / parseInt(prev.num2),
    }));
  };

  return (
    <div className={styles.container}>
      {/* Head section for metadata */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Result display */}
      <div className={styles.result} data-testid="result">
        {state.result}
      </div>

      {/* Input fields for numbers */}
      <input
        type="number"
        className={styles.input}
        data-testid="num1"
        value={state.num1}
        onChange={(e) => setState({ ...state, num1: e.target.value })}
      />
      <input
        type="number"
        className={styles.input}
        data-testid="num2"
        value={state.num2}
        onChange={(e) => setState({ ...state, num2: e.target.value })}
      />

      {/* Buttons for arithmetic operations */}
      <button onClick={add} className={styles.button} data-testid="add">
        Add
      </button>
      <button
        onClick={subtract}
        className={styles.button}
        data-testid="subtract"
      >
        Subtract
      </button>
      <button
        onClick={multiply}
        className={styles.button}
        data-testid="multiply"
      >
        Multiply
      </button>
      <button onClick={divide} className={styles.button} data-testid="divide">
        Divide
      </button>
    </div>
  );
}
